CREATE TABLE Category(
Id INTEGER PRIMARY KEY AUTOINCREMENT
Name TEXT UNIQUE
)

CREATE TABLE "TRANSACTIONS" (
"Id" INTEGER NOT NULL,
"Name" TEXT NOTNULL,
"TransactionType" INT NOTNULL,
"CategoryId" INT NOTNULL,
"Amount" TEXT NOTNULL,

PRIMARY KEY("Id" AUTOINCREMENT),
FOREIGN KEY("CategoryId") REFERENCES "Category"("Id") ON DELETE CASCADE
)